# Generated by Django 4.1.6 on 2024-03-31 18:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import fibas.storage
import fibas.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExecuteCustomMacros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ExecuteMacros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ExecuteQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ExecuteSql',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fibas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(editable=False, max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('date_upload', models.DateTimeField(default=django.utils.timezone.now)),
                ('claims', models.FileField(blank=True, default=None, max_length=500, null=True, storage=fibas.storage.OverwriteStorage(), upload_to=fibas.utils.claims_path_name, validators=[django.core.validators.FileExtensionValidator(['csv']), fibas.utils.validate_filename_claims])),
                ('claims_basic', models.FileField(blank=True, default=None, max_length=500, null=True, storage=fibas.storage.OverwriteStorage(), upload_to=fibas.utils.claims_basic_path_name, validators=[django.core.validators.FileExtensionValidator(['csv']), fibas.utils.validate_filename_claims_basic])),
                ('claims_policy', models.FileField(blank=True, default=None, max_length=500, null=True, storage=fibas.storage.OverwriteStorage(), upload_to=fibas.utils.claims_policy_path_name, validators=[django.core.validators.FileExtensionValidator(['csv']), fibas.utils.validate_filename_claims_policy])),
                ('policies', models.FileField(blank=True, default=None, max_length=500, null=True, storage=fibas.storage.OverwriteStorage(), upload_to=fibas.utils.policies_path_name, validators=[django.core.validators.FileExtensionValidator(['csv']), fibas.utils.validate_filename_policies])),
            ],
            options={
                'verbose_name_plural': 'Fibas',
            },
        ),
        migrations.CreateModel(
            name='User_Custom_Macros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_custom_macros', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserMacros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_macros', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserSql',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('query', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('query_file', models.FileField(blank=True, null=True, storage=fibas.storage.OverwriteStorage(), upload_to=fibas.utils.upload_queries_temp)),
                ('fibas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_queries', to='fibas.fibas')),
            ],
        ),
        migrations.CreateModel(
            name='UserMacrosSql',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, null=True)),
                ('user_macros', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fibas.usermacros')),
                ('user_sql', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fibas.usersql')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='usermacros',
            name='user_sql',
            field=models.ManyToManyField(through='fibas.UserMacrosSql', to='fibas.usersql'),
        ),
        migrations.CreateModel(
            name='UserCustomMacrosSql',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, null=True)),
                ('fibas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_custom_macros', to='fibas.fibas')),
                ('user_custom_macros', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fibas.user_custom_macros')),
                ('user_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fibas.userquery')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='user_custom_macros',
            name='user_query',
            field=models.ManyToManyField(through='fibas.UserCustomMacrosSql', to='fibas.userquery'),
        ),
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val_dat', models.DateTimeField(verbose_name='ValDat')),
                ('val_dat_old', models.DateTimeField(blank=True, default=None, null=True)),
                ('product_type', models.CharField(choices=[('new', 'new'), ('old', 'old')], default='new', max_length=3)),
                ('max_disable', models.IntegerField(default=1)),
                ('fibas', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fibas.fibas')),
            ],
            options={
                'verbose_name_plural': 'Parameters',
            },
        ),
        migrations.CreateModel(
            name='ExcelFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=500, null=True, storage=fibas.storage.OverwriteStorage(), upload_to=fibas.utils.monet_result_all_path_name, validators=[django.core.validators.FileExtensionValidator(['xlsx'])])),
                ('fibas', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fibas.fibas')),
            ],
            options={
                'verbose_name_plural': 'ExcelFile',
            },
        ),
    ]
