# Generated by Django 4.1.6 on 2024-03-31 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fibas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercustommacrossql',
            name='fibas',
        ),
        migrations.AddField(
            model_name='user_custom_macros',
            name='fibas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_custom_macros', to='fibas.fibas'),
        ),
    ]
