# Generated by Django 4.1.6 on 2024-04-08 12:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fibas', '0002_remove_usercustommacrossql_fibas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquery',
            name='applied_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
