# Generated by Django 4.1.6 on 2024-04-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fibas', '0003_userquery_applied_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquery',
            name='applied_at',
            field=models.DateTimeField(null=True),
        ),
    ]
