# Generated by Django 4.1.6 on 2024-04-10 13:31

from django.db import migrations, models
import fibas.utils


class Migration(migrations.Migration):

    dependencies = [
        ('fibas', '0004_alter_userquery_applied_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquery',
            name='query_file',
            field=models.FileField(blank=True, null=True, upload_to=fibas.utils.upload_queries_temp),
        ),
    ]
